#include <stdio.h>
#include <stdlib.h>
#include "../include/knapsack.h"

int main(int argc, char* argv[]) {
    // 1. Validate command line arguments
    if (argc < 3) {
        printf("Usage: ./knapsack_solver <file> <mode>\n");
        return 1;
    }

    // 2. Parse the input file generated by Java
    int N, W;
    Item* items = parseKnapsackInput(argv[1], &N, &W);
    int mode = atoi(argv[2]);

    if (!items) {
        printf("[Error] Failed to parse input file.\n");
        return 1;
    }

    // 3. Initialize tracking variables
    int* finalSelection = (int*)calloc(N, sizeof(int));
    int finalProfit = 0;

    printf("[Backend] Knapsack Items: %d, Capacity: %d\n", N, W);

    // 4. Route to the correct algorithmic engine
    if (mode == 1) {
        // --- MODE 1: PURE B&B (Exact but slow for large N) ---
        printf("[Backend] Mode: Pure Branch & Bound (Exact)\n");
        finalProfit = solveKnapsackBB(items, N, W, 0, finalSelection);
        
    } else if (mode == 2) {
        // --- MODE 2: GREEDY DENSITY (Extremely fast approximation) ---
        printf("[Backend] Mode: Greedy Density Heuristic\n");
        finalProfit = solveGreedy(items, N, W, finalSelection);
        
    } else if (mode == 3) {
        // --- MODE 3: ADVANCED CORE-PROBLEM HYBRID (Fast and Exact) ---
        printf("[Backend] Mode: Advanced Core-Problem Hybrid\n");
        finalProfit = solveKnapsack_AdvancedHybrid(items, N, W, finalSelection);
        
    } else {
        printf("[Error] Invalid algorithm mode selected: %d\n", mode);
    }

    printf("[Backend] Task Complete. Best Profit: %d\n", finalProfit);

    // 5. Write the final results to CSV for Java to read
    writeKnapsackSolution("solution_knapsack.csv", finalProfit, finalSelection, N);

    // 6. Prevent memory leaks
    free(items);
    free(finalSelection);
    
    return 0;
}