#include <stdio.h>
#include <stdlib.h>
#include "../include/knapsack.h"

int main(int argc, char* argv[]) {
    // command line arguments
    if (argc < 3) {
        printf("Usage: ./knapsack_solver <file> <mode>\n");
        return 1;
    }

    //Parse the input file generated by Java
    int N, W;
    Item* items = parseKnapsackInput(argv[1], &N, &W);
    int mode = atoi(argv[2]);

    if (!items) {
        printf("[Error] Failed to parse input file.\n");
        return 1;
    }

    // Initialize tracking variables
    int* finalSelection = (int*)calloc(N, sizeof(int));
    int finalProfit = 0;

    printf("[Backend] Knapsack Items: %d, Capacity: %d\n", N, W);

    //Route to the correct algorithmic engine
    if (mode == 1) {
        printf("[Backend] Mode: Pure Branch & Bound (Exact)\n");
        finalProfit = solveKnapsackBB(items, N, W, 0, finalSelection);
        
    } else if (mode == 2) {
        printf("[Backend] Mode: Greedy Density Heuristic\n");
        finalProfit = solveGreedy(items, N, W, finalSelection);
        
    } else if (mode == 3) {
        printf("[Backend] Mode: Advanced Core-Problem Hybrid\n");
        finalProfit = solveKnapsack_AdvancedHybrid(items, N, W, finalSelection);
        
    } else {
        printf("[Error] Invalid algorithm mode selected: %d\n", mode);
    }

    printf("[Backend] Task Complete. Best Profit: %d\n", finalProfit);

    // Write the final results to CSV for Java to read
    writeKnapsackSolution("solution_knapsack.csv", finalProfit, finalSelection, N);

    //Prevent memory leaks
    free(items);
    free(finalSelection);
    
    return 0;
}